### ISSUE TITLE
Project licence

### ISSUE THREAD

**Issue by jellz** [dninomiya/full-calendar-for-shadcn-ui#7]
Hi, this project looks great and I was wondering if you were intending to put a licence on the project? such as MIT ([the licence shadcn UI uses](https://github.com/shadcn-ui/ui/blob/main/LICENSE.md))

Just wondering because until a licence is added, it's a legal grey area for us to use the component 😄 since no rights are available for others to use the software

Thanks!

**Comment by dninomiya** [comment]
@jellz 
Thank you for the request! I’ve added it.
Feel free to use, modify, and redistribute as you like 😎
