### ISSUE TITLE
is there away to show the current time indicator in the week view 

### ISSUE THREAD

**Issue by Rvey** [dninomiya/full-calendar-for-shadcn-ui#8]
something like this 
<img width="1265" alt="image" src="https://github.com/user-attachments/assets/d1c8c4a9-d22f-4fe5-8fdf-7c15ba34ed1a">
 thanks

**Comment by dninomiya** [comment]
Thank you for the request! I’ve added it. Please reopen if it’s not as intended. 😎

<img width="1357" alt="image" src="https://github.com/user-attachments/assets/7a213579-16a6-4222-9a5a-cb71bab8f903">

**Comment by Rvey** [comment]
hello , i manage to achieve that , but is there a way to show it only for current day as u can see it cross over all the days in week view , thanks
